# Monty Hall Problem
**FIZ371 - Scientific & Technical Calculations | 08/03/2021**

Emre S. Tasci <emre.tasci@hacettepe.edu.tr>

In [1]:
import numpy as np
import random

In [2]:
N = 100000

In [3]:
#np.random.seed(371)

In [4]:
tries = np.random.randint(1,4,(N,5))
tries[:,2:5] = 0

In [5]:
tries
    

array([[3, 2, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [3, 1, 0, 0, 0],
       ...,
       [3, 3, 0, 0, 0],
       [3, 1, 0, 0, 0],
       [3, 3, 0, 0, 0]])

In [6]:
filt = tries[:,0]==tries[:,1]

In [7]:
tries[filt]

array([[2, 2, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [3, 3, 0, 0, 0],
       ...,
       [1, 1, 0, 0, 0],
       [3, 3, 0, 0, 0],
       [3, 3, 0, 0, 0]])

In [8]:
for i in np.array(range(N))[filt]:
    possible = np.array([1,2,3])
    possible = possible[possible != tries[i,0]]
    tries[i,2] = random.choice(possible)

for i in np.array(range(N))[filt]:
    possible = np.array([1,2,3])
    possible = possible[possible != tries[i,0]]
    tries[i,3] = 1
    

In [9]:
nfilt = np.invert(filt)

In [10]:
tries[nfilt]

array([[3, 2, 0, 0, 0],
       [3, 1, 0, 0, 0],
       [2, 1, 0, 0, 0],
       ...,
       [2, 1, 0, 0, 0],
       [1, 3, 0, 0, 0],
       [3, 1, 0, 0, 0]])

In [11]:
for i in np.array(range(N))[nfilt]:
    possible = np.array([1,2,3])
    possible = possible[possible != tries[i,0]]
    possible = possible[possible != tries[i,1]]
    tries[i,2] = possible[0]
    tries[i,4] = 1

In [12]:
tries

array([[3, 2, 1, 0, 1],
       [2, 2, 3, 1, 0],
       [3, 1, 2, 0, 1],
       ...,
       [3, 3, 1, 1, 0],
       [3, 1, 2, 0, 1],
       [3, 3, 1, 1, 0]])

In [13]:
print("# of total wins if sticks  : {:} [prob: {:.5f}]"\
      .format(np.sum(tries[:,3]),np.sum(tries[:,3])/N))
print("# of total wins if switches: {:} [prob: {:.5f}]"\
      .format(np.sum(tries[:,4]),np.sum(tries[:,4])/N))

# of total wins if sticks  : 33389 [prob: 0.33389]
# of total wins if switches: 66611 [prob: 0.66611]
